### PR TITLE
Added Profile Info *Fixed*

### PR DESCRIPTION
**Pull request by sandytan10**

### CODE REVIEW

**Comment by DJankauskas** [comment]
Hello, thanks for the contribution! Could you explain why you added `hello.html` and `.gitignore`? I'm not sure that fits best here although I admire your extra effort.

**Comment by sandytan10** [comment]
Hi Darius,

Sorry for the confusion. I didn’t realize that the assignment was under the
License file initially so I tried to edit a random file. I ended up running
into some problems with ‘git commit’ so I tried again with a new file. At
the end I found the actual assignment and submitted all 3. I apologize for
any confusion.

Best,
Sandy Tan

**Comment by DJankauskas** [comment]
No problem. Could you remove the extra files then? I'd like to keep only necessary files in this repo.

**Comment by squirrelsquirrel78** [comment]
go spec web!

**Comment by DJankauskas** [comment]
Thanks for your contribution, and for removing the extraneous files!

**Pull request merged**
