### PR TITLE
Revert "Update README.md"

### PR DESCRIPTION
**Pull request by zFood**
https://github.com/stuyspec/stuyspec.github.io.git

### CODE REVIEW

**Comment by squirrelsquirrel78** [comment]
@JasonLin43212 @zFood why are y'all reverting @sxiao1's stuff?

**Comment by JasonLin43212** [comment]
Wtf I don't remember trying to revert @sxiao1's stuff. I was the one who merged it. Why would I want to revert it...

**Comment by JasonLin43212** [comment]
Should we just close this PR and not merge it?

**Comment by squirrelsquirrel78** [comment]
Sounds good.

**Pull request closed without merging**
