### PR TITLE
Submitting the Github introductory project

### PR DESCRIPTION
**Pull request by justj10**

### CODE REVIEW

**Comment by jason-tung** [comment]
**no description provided man... how are we supposed to figure out what you're doing??**

**Comment by squirrelsquirrel78** [comment]
Those two commits—`Merge branch 'master' into master`—meant there were some merge conflict errors (GitHub couldn't figure out how to add your schpeel into the file), but I resolved them manually. Good work!

**Comment by squirrelsquirrel78** [comment]
@jason-tung treat your peers with some respect you wacko.

@justj10 if you were pull-requesting a random person's repository (meaning, you are trying to change their codebase and contribute open source) you should reference an Issue and add a description that will clearly state why you have changed the code and what it will do. Usually, however, popular repositories will have "Contributing Guidelines" which tell you what format to put your description in.

**Comment by justj10** [comment]
@jkao1 Okay, thanks for the advice!

**Pull request merged**
